/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author lnminh
 */
public class frmInfo extends javax.swing.JDialog {

    /**
     * Creates new form frmInfo
     */
    public frmInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        jlabel10 = new javax.swing.JLabel();
        jlabel11 = new javax.swing.JLabel();
        jlabel12 = new javax.swing.JLabel();
        jlabel13 = new javax.swing.JLabel();
        jlabel14 = new javax.swing.JLabel();
        jlabel15 = new javax.swing.JLabel();
        jlabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblIcon.setBackground(new java.awt.Color(203, 64, 64));
        lblIcon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        lblIcon.setText("THÔNG TIN PHẦN MỀM");
        lblIcon.setToolTipText("");
        lblIcon.setOpaque(true);

        jlabel.setBackground(new java.awt.Color(51, 51, 51));
        jlabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlabel.setForeground(new java.awt.Color(0, 0, 0));
        jlabel.setText("ĐỒ ÁN: THIẾT KẾ PHẦN MỀM QUẢN LÝ BÁN HÀNG");
        jlabel.setToolTipText("");

        jlabel1.setBackground(new java.awt.Color(51, 51, 51));
        jlabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(0, 0, 0));
        jlabel1.setText("GVHD: ");
        jlabel1.setToolTipText("");

        jlabel2.setBackground(new java.awt.Color(51, 51, 51));
        jlabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(0, 0, 0));
        jlabel2.setText("HVTH:");
        jlabel2.setToolTipText("");

        jlabel3.setBackground(new java.awt.Color(51, 51, 51));
        jlabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(0, 0, 0));
        jlabel3.setText("Thầy Nguyễn Đức Thảo");
        jlabel3.setToolTipText("");

        jlabel4.setBackground(new java.awt.Color(51, 51, 51));
        jlabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(0, 0, 0));
        jlabel4.setText("Lê Ngọc Minh");
        jlabel4.setToolTipText("");

        jlabel5.setBackground(new java.awt.Color(51, 51, 51));
        jlabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(0, 0, 0));
        jlabel5.setText("Huỳnh Tấn Nhân");
        jlabel5.setToolTipText("");

        jlabel6.setBackground(new java.awt.Color(51, 51, 51));
        jlabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(0, 0, 0));
        jlabel6.setText("Dương Phước Thiệm");
        jlabel6.setToolTipText("");

        jlabel8.setBackground(new java.awt.Color(51, 51, 51));
        jlabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(0, 0, 0));
        jlabel8.setText("Email:");
        jlabel8.setToolTipText("");

        jlabel9.setBackground(new java.awt.Color(51, 51, 51));
        jlabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel9.setForeground(new java.awt.Color(0, 0, 0));
        jlabel9.setText("Địa chỉ: ");
        jlabel9.setToolTipText("");

        jlabel10.setBackground(new java.awt.Color(51, 51, 51));
        jlabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel10.setForeground(new java.awt.Color(0, 0, 0));
        jlabel10.setText("tuyensinh@softech.vn");
        jlabel10.setToolTipText("");

        jlabel11.setBackground(new java.awt.Color(51, 51, 51));
        jlabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel11.setForeground(new java.awt.Color(0, 0, 0));
        jlabel11.setText("38 Yên Bái, Đà Nẵng");
        jlabel11.setToolTipText("");

        jlabel12.setBackground(new java.awt.Color(51, 51, 51));
        jlabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel12.setForeground(new java.awt.Color(0, 0, 0));
        jlabel12.setText("Số điện thoại");
        jlabel12.setToolTipText("");

        jlabel13.setBackground(new java.awt.Color(51, 51, 51));
        jlabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel13.setForeground(new java.awt.Color(0, 0, 0));
        jlabel13.setText("0236.3.779.779 ");
        jlabel13.setToolTipText("");

        jlabel14.setBackground(new java.awt.Color(51, 51, 51));
        jlabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel14.setForeground(new java.awt.Color(0, 0, 0));
        jlabel14.setText("Website:");
        jlabel14.setToolTipText("");

        jlabel15.setBackground(new java.awt.Color(51, 51, 51));
        jlabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlabel15.setForeground(new java.awt.Color(0, 0, 0));
        jlabel15.setText("https://aptech-danang.edu.vn");
        jlabel15.setToolTipText("");

        jlabel17.setBackground(new java.awt.Color(51, 51, 51));
        jlabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabel17.setForeground(new java.awt.Color(0, 0, 0));
        jlabel17.setText("Hệ Thống Đào Tạo Lập Trình Viên Quốc Tế Softech Aptech");
        jlabel17.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel1)
                                    .addComponent(jlabel2))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel6)
                                    .addComponent(jlabel5)
                                    .addComponent(jlabel3)
                                    .addComponent(jlabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabel9)
                                .addGap(54, 54, 54)
                                .addComponent(jlabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel8)
                                    .addComponent(jlabel14))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel15)
                                    .addComponent(jlabel10)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jlabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jlabel17)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblIcon)
                .addGap(18, 18, 18)
                .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jlabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmInfo dialog = new frmInfo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel10;
    private javax.swing.JLabel jlabel11;
    private javax.swing.JLabel jlabel12;
    private javax.swing.JLabel jlabel13;
    private javax.swing.JLabel jlabel14;
    private javax.swing.JLabel jlabel15;
    private javax.swing.JLabel jlabel17;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel lblIcon;
    // End of variables declaration//GEN-END:variables
}
