/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Confirm;
import controller.ConnectDatabase;
import controller.FileFactory;
import java.awt.Component;
import java.awt.Container;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author lnmin
 */
public class frmMain extends javax.swing.JFrame {

    private ArrayList<Component> listComponents;
    static ArrayList<String> groupfuntions = new ArrayList<>();
    static boolean loginSuccess = false;

    /**
     * Creates new form frmMain
     */
    public frmMain() {

        initComponents();
        initWindows();
        setNameComponets();
        disableComponents();
        listComponents = getListComponents(this);
        FileFactory.loadFile();
        try {
            createFirstAdminAccount();
        } catch (Exception e) {
        }
        addWindowListener(Confirm.exitListener);
    }

    private void initWindows() {
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void setNameComponets() {
        btnLogin.setName("btnlogin");
        btnSignUp.setName("btnSignUp");
        btnEmp.setName("btnEmp");
        btnWareHouse.setName("btnWareHouse");
        btnGRList.setName("btnGRList");
        btnSupplier.setName("btnSupplier");
        btnOrderList.setName("btnOrderList");
        btnCustomer.setName("btnCustomer");
        btnSalary.setName("btnSalary");
        btnSetting.setName("btnSetting");
        btnInfo.setName("btninfo");
    }

    private void disableComponents() {
        btnSignUp.setEnabled(false);
        btnEmp.setEnabled(false);
        btnEmp.setEnabled(false);
        btnWareHouse.setEnabled(false);
        btnGRList.setEnabled(false);
        btnSupplier.setEnabled(false);
        btnOrderList.setEnabled(false);
        btnCustomer.setEnabled(false);
        btnSalary.setEnabled(false);

    }

    public ArrayList<Component> getListComponents(Container container) {
        ArrayList<Component> listComponents = new ArrayList<>();
        Component[] components = container.getComponents();
        for (Component component : components) {

            listComponents.add(component);
            if (component instanceof Container) {
                listComponents.addAll(getListComponents((Container) component));
            }
        }
        return listComponents;
    }

    private void createFirstAdminAccount() {
        if (!isExistAdminAccount()) {
            int result = JOptionPane.showConfirmDialog(this, "chưa có tài khoản quản trị!"
                    + " Bạn có muốn tạo tài khoản?",
                    "xác nhận tạo tài khoản",
                    JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                requestSignUp();
            }

        }
    }

    private boolean isExistAdminAccount() {
        try (Connection conn = ConnectDatabase.getConnectDatabase()) {
            String sql = "{call sp_isExistAdminAccount(?)}";
            try (CallableStatement cstmt = conn.prepareCall(sql)) {

                cstmt.registerOutParameter(1, java.sql.Types.INTEGER);
                cstmt.execute();

                if (cstmt.getInt(1) == 0) {
                    return false;
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối");
        }
        return true;

    }

    public void updateLimitation() {
        for (Component comp : listComponents) {
            for (String buttonName : groupfuntions) {
                if (comp instanceof JButton) {
                    if (buttonName != null) {
                        if (comp.getName().equalsIgnoreCase(buttonName)) {
                            comp.setEnabled(true);
                        }
                    }
                }
            }
        }
        btnLogin.setText("Đăng xuất");
        btnLogin.setIcon(new ImageIcon(getClass().getResource("/img/logout.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnSalary = new javax.swing.JButton();
        btnOrderList = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnWareHouse = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnGRList = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        lblTitle.setBackground(new java.awt.Color(203, 64, 64));
        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("QUẢN LÝ BÁN HÀNG");
        lblTitle.setOpaque(true);

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnTitle, java.awt.BorderLayout.NORTH);

        pnMain.setBackground(new java.awt.Color(39, 35, 35));
        pnMain.setForeground(new java.awt.Color(255, 153, 0));

        btnLogin.setBackground(new java.awt.Color(232, 177, 67));
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        btnLogin.setText("ĐĂNG NHẬP");
        btnLogin.setContentAreaFilled(false);
        btnLogin.setOpaque(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(35, 197, 206));
        btnSignUp.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registration.png"))); // NOI18N
        btnSignUp.setText("ĐĂNG KÝ");
        btnSignUp.setContentAreaFilled(false);
        btnSignUp.setOpaque(true);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnEmp.setBackground(new java.awt.Color(30, 165, 165));
        btnEmp.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employee.png"))); // NOI18N
        btnEmp.setText("NHÂN VIÊN");
        btnEmp.setContentAreaFilled(false);
        btnEmp.setOpaque(true);
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        btnSalary.setBackground(new java.awt.Color(18, 185, 45));
        btnSalary.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSalary.setForeground(new java.awt.Color(255, 255, 255));
        btnSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salary.png"))); // NOI18N
        btnSalary.setText("QUẢN LÝ LƯƠNG");
        btnSalary.setContentAreaFilled(false);
        btnSalary.setOpaque(true);
        btnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryActionPerformed(evt);
            }
        });

        btnOrderList.setBackground(new java.awt.Color(27, 157, 221));
        btnOrderList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOrderList.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sale.png"))); // NOI18N
        btnOrderList.setText("ĐƠN XUẤT");
        btnOrderList.setContentAreaFilled(false);
        btnOrderList.setMaximumSize(new java.awt.Dimension(240, 80));
        btnOrderList.setMinimumSize(new java.awt.Dimension(240, 80));
        btnOrderList.setOpaque(true);
        btnOrderList.setPreferredSize(new java.awt.Dimension(240, 80));
        btnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderListActionPerformed(evt);
            }
        });

        btnSupplier.setBackground(new java.awt.Color(27, 112, 218));
        btnSupplier.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supplier.png"))); // NOI18N
        btnSupplier.setText("NHÀ CUNG CẤP");
        btnSupplier.setContentAreaFilled(false);
        btnSupplier.setMaximumSize(new java.awt.Dimension(240, 80));
        btnSupplier.setMinimumSize(new java.awt.Dimension(240, 80));
        btnSupplier.setOpaque(true);
        btnSupplier.setPreferredSize(new java.awt.Dimension(240, 80));
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnWareHouse.setBackground(new java.awt.Color(23, 187, 146));
        btnWareHouse.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnWareHouse.setForeground(new java.awt.Color(255, 255, 255));
        btnWareHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/warehouse.png"))); // NOI18N
        btnWareHouse.setText("QUẢN LÝ KHO");
        btnWareHouse.setContentAreaFilled(false);
        btnWareHouse.setOpaque(true);
        btnWareHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWareHouseActionPerformed(evt);
            }
        });

        btnCustomer.setBackground(new java.awt.Color(225, 112, 112));
        btnCustomer.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N
        btnCustomer.setText("KHÁCH HÀNG");
        btnCustomer.setContentAreaFilled(false);
        btnCustomer.setMaximumSize(new java.awt.Dimension(240, 80));
        btnCustomer.setMinimumSize(new java.awt.Dimension(240, 80));
        btnCustomer.setOpaque(true);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnGRList.setBackground(new java.awt.Color(232, 134, 96));
        btnGRList.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnGRList.setForeground(new java.awt.Color(255, 255, 255));
        btnGRList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        btnGRList.setText("ĐƠN NHẬP");
        btnGRList.setContentAreaFilled(false);
        btnGRList.setOpaque(true);
        btnGRList.setPreferredSize(new java.awt.Dimension(240, 80));
        btnGRList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGRListActionPerformed(evt);
            }
        });

        btnSetting.setBackground(new java.awt.Color(173, 173, 173));
        btnSetting.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(255, 255, 255));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.png"))); // NOI18N
        btnSetting.setText("CÀI ĐẶT");
        btnSetting.setContentAreaFilled(false);
        btnSetting.setOpaque(true);
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(173, 173, 173));
        btnInfo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        btnInfo.setText("THÔNG TIN");
        btnInfo.setContentAreaFilled(false);
        btnInfo.setOpaque(true);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnWareHouse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMainLayout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMainLayout.createSequentialGroup()
                            .addComponent(btnGRList, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWareHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGRList, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOrderList, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWareHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWareHouseActionPerformed
        frmWareHouse fwh = new frmWareHouse();
        fwh.setLocationRelativeTo(this);
        fwh.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnWareHouseActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        frmSupplier fs = new frmSupplier();
        fs.setLocationRelativeTo(this);
        fs.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnGRListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGRListActionPerformed
        frmGRList fGRL = new frmGRList();
        fGRL.setLocationRelativeTo(this);
        fGRL.setVisible(true);
    }//GEN-LAST:event_btnGRListActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (loginSuccess) {
            requestLogout();

        } else {

            requestLogin();
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    private void requestLogin() {
        frmLogin fl = new frmLogin(this, true);
        fl.setLocationRelativeTo(this);
        fl.setVisible(true);
        if (loginSuccess) {
            updateLimitation();
        };
    }

    private void requestLogout() {
        loginSuccess = false;
        btnLogin.setText("Đăng Nhập");
        btnLogin.setIcon(new ImageIcon(getClass().getResource("/img/login.png")));
        groupfuntions.clear();
        disableComponents();

    }


    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        requestSignUp();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void requestSignUp() {
        frmSignUp fsu = new frmSignUp(this, true);
        fsu.setLocationRelativeTo(this);
        fsu.setVisible(true);
    }
    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        requestFrameEmp();
    }//GEN-LAST:event_btnEmpActionPerformed
    private void requestFrameEmp() {
        frmEmployee fe = new frmEmployee();
        fe.setLocationRelativeTo(this);
        fe.setVisible(true);
    }
    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        frmCustomer fc = new frmCustomer();
        fc.setLocationRelativeTo(this);
        fc.setVisible(true);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderListActionPerformed
        frmOrderList fol = new frmOrderList();
        fol.setLocationRelativeTo(this);
        fol.setVisible(true);
    }//GEN-LAST:event_btnOrderListActionPerformed

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        frmPayroll fp = new frmPayroll();
        fp.setLocationRelativeTo(this);
        fp.setVisible(true);
    }//GEN-LAST:event_btnSalaryActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        requestConfig();
    }//GEN-LAST:event_btnSettingActionPerformed

    private void requestConfig() {
        frmConfig fc = new frmConfig();
        fc.setLocationRelativeTo(this);
        fc.setVisible(true);
    }

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        frmInfo fi = new frmInfo(this, true);
        fi.setLocationRelativeTo(this);
        fi.setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnGRList;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOrderList;
    private javax.swing.JButton btnSalary;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnWareHouse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables

}
